### PR TITLE
Ausleihe

### PR DESCRIPTION
**Pull request by Rustesis**
new features:

    * overview sites for own lendings and borrows

    * can accept lending requests

    * warning if you overdue with your lending time

    * can return a lending

    * sets article to available after return

### CODE REVIEW

**Comment by Robnarok** [comment]
please fix the merge conflict.

Also - Dont use the depricated Date class. Look at Calendar ;)
Theres no update for the Documentation. Please write something down before pushing into the master
Theres no tests ?!

**Comment by Robnarok** [comment]
Good job fixing the Merge conflicts.
Documentation is fine 
You commited  Build files, please fix (Guess its because of the rename. Look at the .gitignore)
still no tests

**Comment by Robnarok** [comment]
Everything is fine now, but still no tests :sweat_smile:

**Comment by Rustesis** [comment]
we will replace the Crudrepository standard methods with specialtailored requests to make it more efficient

**Comment by Robnarok** [comment]
Please start a new pull request, when you finished rewriting your MEthodes

**Pull request closed without merging**
